# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('month_of_birth', models.IntegerField()),
                ('sex', models.CharField(choices=[('Ml', 'Male'), ('Fl', 'Female')], max_length=5)),
                ('education', models.CharField(choices=[('None', 'None'), ('EL', 'Elementary'), ('COL', 'College'), ('BCH', 'Bachelor')], max_length=10)),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('health', models.IntegerField()),
                ('partner_id', models.PositiveIntegerField(default=0)),
                ('father_id', models.PositiveIntegerField(default=0)),
                ('mother_id', models.PositiveIntegerField(default=0)),
                ('workplace_object_id', models.PositiveIntegerField(null=True)),
                ('resident_object_id', models.PositiveIntegerField(null=True)),
                ('school_object_id', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
