# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('income', models.IntegerField()),
                ('health', models.IntegerField()),
                ('object_id', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
