# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 12:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='health',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
