# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0040_auto_20180305_2005'),
        ('citizen_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='production_building',
        ),
        migrations.AddField(
            model_name='citizen',
            name='type_of_work',
            field=models.CharField(choices=[('WP', 'WindPlant'), ('WT', 'WaterTower'), ('PB', 'ProductionBuilding')], default='WT', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='work_in_production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city_engine.ProductionBuilding'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='work_in_watertower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city_engine.WaterTower'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='work_in_windplant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city_engine.WindPlant'),
        ),
    ]
