# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_engine', '0003_auto_20170820_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='health',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=30)]),
        ),
    ]
