# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_engine', '0004_auto_20170820_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='health',
            field=models.IntegerField(),
        ),
    ]
