# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15, unique=True)),
                ('cash', models.IntegerField(default=10000)),
                ('publish', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('if_residential', models.BooleanField(default=False)),
                ('if_production', models.BooleanField(default=False)),
                ('if_service', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.City')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_time', models.IntegerField()),
                ('trash', models.IntegerField()),
                ('health', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('water', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('pollution', models.IntegerField()),
                ('recycling', models.IntegerField()),
                ('city_communication', models.IntegerField()),
                ('current_employees', models.IntegerField()),
                ('max_employees', models.IntegerField()),
                ('production_level', models.IntegerField()),
                ('city_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_time', models.IntegerField()),
                ('trash', models.IntegerField()),
                ('health', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('water', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('pollution', models.IntegerField()),
                ('recycling', models.IntegerField()),
                ('city_communication', models.IntegerField()),
                ('current_population', models.IntegerField()),
                ('max_population', models.IntegerField()),
                ('residential_level', models.IntegerField()),
                ('city_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
