# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
