# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_time', models.IntegerField()),
                ('trash', models.IntegerField()),
                ('health', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('water', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('pollution', models.IntegerField()),
                ('recycling', models.IntegerField()),
                ('city_communication', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('current_employees', models.IntegerField()),
                ('max_employees', models.IntegerField()),
                ('power_nodes', models.IntegerField(default=1)),
                ('energy_production', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='cityfield',
            old_name='if_service',
            new_name='if_electricity',
        ),
        migrations.AddField(
            model_name='powerplant',
            name='city_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField'),
        ),
    ]
