# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionbuilding',
            old_name='residential_level',
            new_name='production_level',
        ),
    ]
