# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0002_auto_20170917_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplant',
            name='city_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField'),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='city_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField'),
        ),
        migrations.AlterField(
            model_name='residential',
            name='city_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField'),
        ),
    ]
