# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0005_auto_20170924_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerplant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productionbuilding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='user',
        ),
        migrations.AddField(
            model_name='powerplant',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city_engine.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city_engine.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residential',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city_engine.City'),
            preserve_default=False,
        ),
    ]
