# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0006_auto_20170924_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplant',
            name='current_build_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='energy_production',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='max_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='power_nodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='current_build_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='residential',
            name='current_build_time',
            field=models.IntegerField(default=1),
        ),
    ]
