# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0007_auto_20171003_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_under_construction', models.BooleanField(default=True)),
                ('build_time', models.IntegerField()),
                ('current_build_time', models.IntegerField(default=1)),
                ('trash', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('crime', models.IntegerField(default=0)),
                ('pollution', models.IntegerField(default=0)),
                ('recycling', models.IntegerField(default=0)),
                ('city_communication', models.IntegerField(default=0)),
                ('current_employees', models.IntegerField(default=0)),
                ('max_employees', models.IntegerField(default=0)),
                ('power_nodes', models.IntegerField(default=0)),
                ('energy_production', models.IntegerField(default=0)),
                ('name', models.CharField(default='Elektrownia wiatrowa', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.City')),
                ('city_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='powerplant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='powerplant',
            name='city_field',
        ),
        migrations.DeleteModel(
            name='PowerPlant',
        ),
    ]
