# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0008_auto_20171003_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windplant',
            name='build_time',
            field=models.IntegerField(default=3),
        ),
    ]
