# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0010_ropeplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ropeplant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='windplant',
            name='build_time',
        ),
        migrations.RemoveField(
            model_name='windplant',
            name='name',
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residential',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
