# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0013_auto_20171008_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coalplant',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='ropeplant',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='windplant',
            name='maintenance_cost',
        ),
    ]
