# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0014_auto_20171008_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='coalplant',
            name='build_cost',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='coalplant',
            name='build_time',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='coalplant',
            name='maintenance_cost',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='coalplant',
            name='name',
            field=models.CharField(default='Elektrownia węglowa', max_length=20),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='build_cost',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='build_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='maintenance_cost',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='name',
            field=models.CharField(default='Elektrownia na ropę', max_length=20),
        ),
        migrations.AddField(
            model_name='windplant',
            name='build_cost',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='windplant',
            name='build_time',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='windplant',
            name='maintenance_cost',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='windplant',
            name='name',
            field=models.CharField(default='Elektrownia wiatrowa', max_length=20),
        ),
    ]
