# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0016_auto_20171008_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
