# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0018_auto_20171009_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='coalplant',
            name='max_power_nodes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='max_power_nodes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='windplant',
            name='max_power_nodes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
