# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0019_auto_20171012_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_under_construction', models.BooleanField(default=True)),
                ('current_build_time', models.PositiveIntegerField(default=1)),
                ('current_employees', models.PositiveIntegerField(default=0)),
                ('max_employees', models.PositiveIntegerField(default=0)),
                ('trash', models.PositiveIntegerField(default=0)),
                ('health', models.PositiveIntegerField(default=0)),
                ('energy', models.PositiveIntegerField(default=0)),
                ('water', models.PositiveIntegerField(default=0)),
                ('crime', models.PositiveIntegerField(default=0)),
                ('pollution', models.PositiveIntegerField(default=0)),
                ('recycling', models.PositiveIntegerField(default=0)),
                ('city_communication', models.PositiveIntegerField(default=0)),
                ('water_production', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='Wieża ciśnień', max_length=20)),
                ('build_time', models.PositiveIntegerField(default=1)),
                ('build_cost', models.PositiveIntegerField(default=50)),
                ('maintenance_cost', models.PositiveIntegerField(default=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.City')),
                ('city_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_engine.CityField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='residential',
            name='current_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residential',
            name='max_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='max_employees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
