# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0020_auto_20171015_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityfield',
            name='if_waterworks',
            field=models.BooleanField(default=False),
        ),
    ]
