# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0022_auto_20171016_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='energy_production',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='water_production',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
