# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0023_auto_20171017_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertower',
            name='energy_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
