# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0024_watertower_energy_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='coalplant',
            name='energy_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='energy_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residential',
            name='energy_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='energy_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='windplant',
            name='energy_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watertower',
            name='energy_required',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
