# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0025_auto_20171017_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='energy_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
