# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0028_auto_20171029_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='coalplant',
            name='energy_allocated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='energy_allocated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='windplant',
            name='energy_allocated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
