# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0029_auto_20171029_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='coalplant',
            name='water_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='water_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residential',
            name='water_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='water_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watertower',
            name='water_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='windplant',
            name='water_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
