# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0030_auto_20171112_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertower',
            name='total_water_production',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watertower',
            name='water_allocated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coalplant',
            name='water_required',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='ropeplant',
            name='water_required',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='windplant',
            name='water_required',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
