# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0031_auto_20171112_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='energy_production',
        ),
        migrations.RemoveField(
            model_name='city',
            name='energy_used',
        ),
        migrations.RemoveField(
            model_name='cityfield',
            name='field_id',
        ),
        migrations.AddField(
            model_name='cityfield',
            name='col',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityfield',
            name='row',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
