# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0032_auto_20171119_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='water_production',
        ),
        migrations.RemoveField(
            model_name='cityfield',
            name='if_electricity',
        ),
        migrations.RemoveField(
            model_name='cityfield',
            name='if_production',
        ),
        migrations.RemoveField(
            model_name='cityfield',
            name='if_residential',
        ),
        migrations.RemoveField(
            model_name='cityfield',
            name='if_waterworks',
        ),
        migrations.AddField(
            model_name='coalplant',
            name='if_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coalplant',
            name='if_waterworks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='if_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='if_waterworks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residential',
            name='if_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residential',
            name='if_waterworks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='if_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='if_waterworks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watertower',
            name='if_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watertower',
            name='if_waterworks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windplant',
            name='if_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windplant',
            name='if_waterworks',
            field=models.BooleanField(default=False),
        ),
    ]
