# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0034_auto_20180225_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coalplant',
            old_name='if_reidential',
            new_name='if_residential',
        ),
        migrations.RenameField(
            model_name='coalplant',
            old_name='if_waterterworks',
            new_name='if_waterworks',
        ),
        migrations.RenameField(
            model_name='productionbuilding',
            old_name='if_reidential',
            new_name='if_residential',
        ),
        migrations.RenameField(
            model_name='productionbuilding',
            old_name='if_waterterworks',
            new_name='if_waterworks',
        ),
        migrations.RenameField(
            model_name='residential',
            old_name='if_reidential',
            new_name='if_residential',
        ),
        migrations.RenameField(
            model_name='residential',
            old_name='if_waterterworks',
            new_name='if_waterworks',
        ),
        migrations.RenameField(
            model_name='ropeplant',
            old_name='if_reidential',
            new_name='if_residential',
        ),
        migrations.RenameField(
            model_name='ropeplant',
            old_name='if_waterterworks',
            new_name='if_waterworks',
        ),
        migrations.RenameField(
            model_name='watertower',
            old_name='if_reidential',
            new_name='if_residential',
        ),
        migrations.RenameField(
            model_name='watertower',
            old_name='if_waterterworks',
            new_name='if_waterworks',
        ),
        migrations.RenameField(
            model_name='windplant',
            old_name='if_reidential',
            new_name='if_residential',
        ),
        migrations.RenameField(
            model_name='windplant',
            old_name='if_waterterworks',
            new_name='if_waterworks',
        ),
    ]
