# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0035_auto_20180225_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coalplant',
            name='if_electricity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ropeplant',
            name='if_electricity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='watertower',
            name='if_waterworks',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='windplant',
            name='if_electricity',
            field=models.BooleanField(default=True),
        ),
    ]
