# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0036_auto_20180225_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coalplant',
            old_name='pollution',
            new_name='pollution_product',
        ),
        migrations.RenameField(
            model_name='productionbuilding',
            old_name='pollution',
            new_name='pollution_product',
        ),
        migrations.RenameField(
            model_name='residential',
            old_name='current_population',
            new_name='pollution_product',
        ),
        migrations.RenameField(
            model_name='residential',
            old_name='pollution',
            new_name='population',
        ),
        migrations.RenameField(
            model_name='ropeplant',
            old_name='pollution',
            new_name='pollution_product',
        ),
        migrations.RenameField(
            model_name='watertower',
            old_name='pollution',
            new_name='pollution_product',
        ),
        migrations.RenameField(
            model_name='windplant',
            old_name='pollution',
            new_name='pollution_product',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='residential_level',
        ),
        migrations.AddField(
            model_name='cityfield',
            name='pollution',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='zone_value',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='$', max_length=3),
        ),
        migrations.AddField(
            model_name='residential',
            name='zone_value',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='$', max_length=3),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='if_production',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='if_under_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residential',
            name='if_residential',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='residential',
            name='if_under_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residential',
            name='max_population',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
