# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0037_auto_20180301_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watertower',
            name='total_water_production',
        ),
        migrations.AddField(
            model_name='productionbuilding',
            name='pollution_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='residential',
            name='pollution_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
