# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0039_auto_20180304_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionbuilding',
            name='production_level',
        ),
        migrations.RemoveField(
            model_name='productionbuilding',
            name='zone_value',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='current_employees',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='max_employees',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='zone_value',
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='build_cost',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='build_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='if_under_construction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='maintenance_cost',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='productionbuilding',
            name='max_employees',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='residential',
            name='build_cost',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='residential',
            name='build_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='residential',
            name='if_under_construction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='residential',
            name='maintenance_cost',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='residential',
            name='max_population',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
