# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0040_auto_20180305_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbuilding',
            name='name',
            field=models.CharField(default='Budynek Przemysłowy', max_length=20),
        ),
        migrations.AddField(
            model_name='residential',
            name='name',
            field=models.CharField(default='Budynek Mieszkalny', max_length=20),
        ),
    ]
