# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0042_auto_20180314_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='coalplant',
            name='type_of_building',
            field=models.CharField(default='CP', max_length=2),
        ),
        migrations.AddField(
            model_name='ropeplant',
            name='type_of_building',
            field=models.CharField(default='RP', max_length=2),
        ),
        migrations.AddField(
            model_name='watertower',
            name='type_of_building',
            field=models.CharField(default='WT', max_length=2),
        ),
        migrations.AddField(
            model_name='windplant',
            name='type_of_building',
            field=models.CharField(default='WP', max_length=2),
        ),
    ]
