# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0043_auto_20180319_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coalplant',
            old_name='type_of_building',
            new_name='type_of_working_building',
        ),
        migrations.RenameField(
            model_name='ropeplant',
            old_name='type_of_building',
            new_name='type_of_working_building',
        ),
        migrations.RenameField(
            model_name='watertower',
            old_name='type_of_building',
            new_name='type_of_working_building',
        ),
        migrations.RenameField(
            model_name='windplant',
            old_name='type_of_building',
            new_name='type_of_working_building',
        ),
    ]
