# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('city_engine', '0045_productionbuilding_type_of_working_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=0)),
                ('time', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='coalplant',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='productionbuilding',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='ropeplant',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='watertower',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='windplant',
            name='trash',
        ),
    ]
