# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0046_auto_20180323_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coalplant',
            name='city_communication',
        ),
        migrations.RemoveField(
            model_name='coalplant',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='coalplant',
            name='health',
        ),
        migrations.RemoveField(
            model_name='productionbuilding',
            name='city_communication',
        ),
        migrations.RemoveField(
            model_name='productionbuilding',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='productionbuilding',
            name='health',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='city_communication',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='health',
        ),
        migrations.RemoveField(
            model_name='ropeplant',
            name='city_communication',
        ),
        migrations.RemoveField(
            model_name='ropeplant',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='ropeplant',
            name='health',
        ),
        migrations.RemoveField(
            model_name='watertower',
            name='city_communication',
        ),
        migrations.RemoveField(
            model_name='watertower',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='watertower',
            name='health',
        ),
        migrations.RemoveField(
            model_name='windplant',
            name='city_communication',
        ),
        migrations.RemoveField(
            model_name='windplant',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='windplant',
            name='health',
        ),
    ]
