# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 11:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0047_auto_20180323_1836'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coalplant',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productionbuilding',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='residential',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ropeplant',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='watertower',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='windplant',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
