# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_engine', '0048_auto_20180325_1149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coalplant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productionbuilding',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='residential',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ropeplant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='watertower',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='windplant',
            managers=[
            ],
        ),
    ]
